name: Deploy js project to vps with nginx

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Inspect build (debug)
        run: |
          echo "=== dist list ==="
          ls -la dist || true
          echo "=== Search for fetch in build ==="
          grep -R "fetch(" dist || true
          echo "GITHUB_SHA=${GITHUB_SHA}" > dist/version.txt
          echo "BUILT_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> dist/version.txt
          head -n 40 dist/index.html || true  

      - name: Deploy build files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "dist/*"
          target: ${{ secrets.VPS_PATH_DIR }}
          rm: true
